application: swined-test
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
- url: /i
  script: img.py
- url: /i/u
  script: img.py
  login: required
- url: /i/[0-9]+
  script: img.py
