#!/bin/sh

die() {
    echo $1
    exit 1
}

svn commit -m 'auto commit' || die commit failed
svn-buildpackage -rfakeroot -us -uc --svn-move-to $PWD || die build failed
sudo dpkg -i webtornado_*_i386.deb || die installation failed
