.TH "LJ2MAIL" "8" 
.SH "NAME" 
lj2mail \(em LiveJournal friendlist tracker 
.SH "SYNOPSIS" 
.PP 
\fBcd [work-dir] && lj2mail\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the \fBlj2mail\fR command. 
.PP 
\fBlj2mail\fR is a tool that keeps track of your LiveJournal friendlist and mails new entries.
.SH "OPTIONS" 
.PP 
This program takes no options and is fully controlled by it's config file. 
.SH "CONFIGURATION" 
.PP 
Configuration can be done by editing [work-dir]/lj2mail.conf
.PP
Sample config file is located at /usr/share/lj2mail/lj2mail.conf.sample
.SH "SEE ALSO" 
.PP 
lj2mail.conf (8). 
.SH "AUTHOR" 
.PP 
This manual page was written by Alexey Alexandrov <swined@gmail.com> for 
the \fBDebian GNU/Linux\fP system (but may be used by others). 
This manual is free software; you can redistribute it and/or modify 
it under the terms of the GNU General Public License as published by 
the Free Software Foundation; either version 2 of the License, or 
(at your option) any later version. 
